services:
  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php_web2
    ports:
      - "8083:80"
    volumes:
      - .:/var/www/html
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${MONGO_DB}
      REDIS_URL: redis://host.docker.internal:6379
      RABBITMQ_HOST: host.docker.internal   
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRY: ${JWT_EXPIRY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  game_start_consumer:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php_game_consumer
    volumes:
      - .:/var/www/html
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${MONGO_DB}
      REDIS_URL: redis://host.docker.internal:6379
      RABBITMQ_HOST: host.docker.internal
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRY: ${JWT_EXPIRY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /var/www/html
    command: php bin/start_game_consumer.php
    restart: unless-stopped